version: "2"

services:
  dashboard:
    build: ./dashboard
    command: npm run prod -s
    volumes:
     - ./dashboard:/usr/src/app
    container_name: sway-dashboard
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

  server:
    build: ./server
    command: npm start
    volumes:
     - ./server:/usr/src/app
    container_name: sway-server
    ports:
      - "8081:8081"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: sway-redis
    ports: ["6379"]
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
